CXX = g++
BINARIES = MyChunkyList, MyChunkyNode

hellomake: MyChunkyList.cpp
	g++ -o MyChunkyList MyChunkyList.cpp
hellomake: MyChunkyNode.cpp
	g++ -o MyChunkyNode MyChunkyNode.cpp
clean:
	/bin/rm -f ${BINARIES} *.o
