CXX = g++
BINARIES = MyChunkyList, MyChunkyNode, main

hellomake: MyChunkyList.cpp
	g++ -o MyChunkyList MyChunkyList.cpp
hellomake: MyChunkyNode.cpp
	g++ -o MyChunkyNode MyChunkyNode.cpp
hellomake: main.cpp
	g++ -o main main.cpp
clean:
	/bin/rm -f ${BINARIES} *.o
